 # creation rules are evaluated sequentially, the first match wins
 creation_rules:
         # upon creation of a file that matches the pattern *.dev.yaml,
         - path_regex: \.dev\.yaml$
           pgp: '4FBC3F744F787B5ECBAD88C3D932F46E6F43D00A'

         # upon creation of a file that matches the pattern *.prod.yamlM
         - path_regex: \.prod\.yaml$
           gcp_kms: projects/k8s-the-hard-way-222322/locations/global/keyRings/sops/cryptoKeys/sops-key
         # everythin else
         - pgp: 'C9CAB0AF1165060DB58D6D6B2653B624D620786D'
